version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile      

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
      
    ports:
      - 2000:80


