version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      
    volumes:
      - /frontend/node_modules
      - ./frontend/src:/app/frontend/src
    
    ports:
      - 3000:3000
    environment: 
      - CHOKIDAR_USEPOLLING=true  
    
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    
    volumes:
      - ./backend:/app
    ports:
      - 5000:5000     