version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      
    volumes:
      - /frontend/node_modules
      - ./frontend/src:/app/frontend/src
    
    ports:
      - 3000:3000
    environment: 
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true  
    
    stdin_open: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    
    volumes:
      - /backend/node_modules
      - ./backend:/app
    ports:
      - 5000:5000     

  flask:
    build:
      context: ./flask_api
      dockerfile: Dockerfile
    volumes:
      - ./flask_api:/app  
    ports:
      - 4000:4000      

  nginx:
    restart: always
    depends_on: 
      - frontend
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - /var/cache/nginx  
    ports:
      - 2000:80     